[package]
name = "genz"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/dmkolobov/genz"
readme = "README.md"
description = "Uniqueness of types via invariant lifetimes."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
